spring:
  datasource:
    url: jdbc:mysql://${datalink.datasource.ip}:3306/datalink?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: ${datalink.datasource.username}
    password: ${datalink.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.datalink.base.model,com.datalink.task.entity
  global-config:
    db-config:
      id-type: auto

datalink:
  swagger:
    enabled: true
    title: 作业中心
    description: 作业中心接口文档
    version: 1.0
    base-package: com.datalink.task.controller
  tenant:
    enable: true
    ignoreTables:
    ignoreSqls: